import { UntypedFormControl } from '@angular/forms';
// @ts-ignore
import { Validators } from '@angular/forms';
// @ts-ignore
import { hexadecimalValidator } from '@shared/directives/hexadecimal.directive';
// @ts-ignore
import { ipValidator } from '@shared/directives/ip.directive';

export const Fse18283_springcore_h518_afcare_twoFormGroup = {
    reg02c0_m6awtjl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c0_eph722y: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c0_kspmojd: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c1_m6awtjl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c1_5ymphln_op23zml: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c1_5ymphln_ax7h6sl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c1_5ymphln_t6r55rl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c1_5ymphln_eph722y: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c1_gcbfcky_riuquxn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c1_5ymphln_khxezgy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c2_m6awtjl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c2_bozlrly_op23zml: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c2_bozlrly_ax7h6sl: new UntypedFormControl({ value: "1", disabled: false}),
    reg02c2_bozlrly_t6r55rl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c2_bozlrly_eph722y: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c2_bozlrly_riuquxn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c2_bozlrly_khxezgy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c4_snvp4xd: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c4_s27wvjn_ooba6wy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c5_vtrhxcd: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c5_s5gikod: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c5_yzwk5zd: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c5_zgpuoyd: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c5_6xkls3d: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c5_54cmvpd: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c5_5pbdr5n: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c5_5r4ewkl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c5_gsqqlyn: new UntypedFormControl({ value: "02", disabled: false}, [hexadecimalValidator(null, null)]),
    reg02c5_rk4pgmy: new UntypedFormControl({ value: "03", disabled: false}, [hexadecimalValidator(null, null)]),
    reg02cd: new UntypedFormControl({ value: "00000000", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(8), Validators.maxLength(8)]),
    reg02ce_fe5kedn_kxpbr2l: new UntypedFormControl({ value: "0", disabled: false}),
    reg02ce_fe5kedn_ax7h6sl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02ce_fe5kedn_t6r55rl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02ce_fe5kedn_l365cmn: new UntypedFormControl({ value: "0", disabled: false}),
    reg0208: new UntypedFormControl({ value: "", disabled: false}, [Validators.maxLength(32)]),
    reg02d0_snvp4xd: new UntypedFormControl({ value: "0", disabled: false}),
    reg02d0_ooba6wy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02d1: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(2), Validators.maxLength(2)]),
    reg02d2_3iq5wdd: new UntypedFormControl({ value: "9", disabled: false}),
    reg02d2_ai7xezy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02d2_gjrcb2n: new UntypedFormControl({ value: "2", disabled: false}),
    reg02d2_5sqf4yy: new UntypedFormControl({ value: "10", disabled: false}),
    reg02d2_k4uiain: new UntypedFormControl({ value: "0", disabled: false}),
    reg02d2_evlcwsl: new UntypedFormControl({ value: "1", disabled: false}),
    reg02d3_lmh6e5y: new UntypedFormControl({ value: "100", disabled: false}),
    reg02d3_gsqqlyn: new UntypedFormControl({ value: "75", disabled: false}),
    reg02d3_rk4pgmy: new UntypedFormControl({ value: "10", disabled: false}),
    reg02d7: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(2), Validators.maxLength(2)]),
    reg02d8_hxqkjly: new UntypedFormControl({ value: "0", disabled: false}),
    reg02d8_kspmojd: new UntypedFormControl({ value: "01", disabled: false}, [hexadecimalValidator(null, null)]),
    reg02d9: new UntypedFormControl({ value: "", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(0), Validators.maxLength(128)]),
    reg02da: new UntypedFormControl({ value: "000000", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(6), Validators.maxLength(6)]),
    reg02f0_y4yzkmn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_3m2xxun: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_noupivn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_xajyakn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_ctwu2dn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_ch4wbsl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_vjvofiy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_rc6tnwl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_5y4fpey: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_awfi3xn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_loo4own: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_4koytuy: new UntypedFormControl({ value: "0", disabled: false}),
    id273_Note: new UntypedFormControl({ value: "", disabled: false}),
    reg02f1_3iq5wdd: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f1_ytndzhn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f1_5sqf4yy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f1_rxpn6ed: new UntypedFormControl({ value: "0", disabled: false}),
    reg0240: new UntypedFormControl({ value: "80", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(2), Validators.maxLength(2)]),
    reg0241_bozlrly_rx2tm2y: new UntypedFormControl({ value: "0006", disabled: false}, [hexadecimalValidator(null, null)]),
    reg0241_bozlrly_kf4jw3l: new UntypedFormControl({ value: "0006", disabled: false}, [hexadecimalValidator(null, null)]),
    reg0241_bozlrly_n756ral: new UntypedFormControl({ value: "0000", disabled: false}, [hexadecimalValidator(null, null)]),
    reg0241_bozlrly_ehbhexd: new UntypedFormControl({ value: "0064", disabled: false}, [hexadecimalValidator(null, null)]),
    reg0242: new UntypedFormControl({ value: "1E", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(2), Validators.maxLength(2)]),
    reg0243_bozlrly_hycivfd: new UntypedFormControl({ value: "0", disabled: false}),
    reg0243_bozlrly_mdwlall: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null)]),
    reg0243_bozlrly_ooba6wy: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null)]),
    reg0248_bozlrly_m6awtjl: new UntypedFormControl({ value: "1", disabled: false}),
    reg0248_bozlrly_dlvtahl: new UntypedFormControl({ value: "07", disabled: false}, [hexadecimalValidator(null, null)]),
    reg0248_bozlrly_eph722y: new UntypedFormControl({ value: "0", disabled: false}),
    reg0248_bozlrly_kspmojd: new UntypedFormControl({ value: "07", disabled: false}, [hexadecimalValidator(null, null)]),
    reg0249: new UntypedFormControl({ value: "00000000", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(8), Validators.maxLength(8)]),
    reg0271_m6awtjl: new UntypedFormControl({ value: true, disabled: false}),
    reg0271_op23zml: new UntypedFormControl({ value: true, disabled: false}),
    reg0271_6pga6ll: new UntypedFormControl({ value: "0", disabled: false}),
    reg0271_eph722y: new UntypedFormControl({ value: "0", disabled: false}),
    reg0271_kspmojd: new UntypedFormControl({ value: "3", disabled: false}),
    reg0272_m6awtjl: new UntypedFormControl({ value: true, disabled: false}),
    reg0272_op23zml: new UntypedFormControl({ value: true, disabled: false}),
    reg0272_6pga6ll: new UntypedFormControl({ value: "0", disabled: false}),
    reg0272_eph722y: new UntypedFormControl({ value: "0", disabled: false}),
    reg0272_kspmojd: new UntypedFormControl({ value: "2", disabled: false}),
    reg0273_m6awtjl: new UntypedFormControl({ value: true, disabled: false}),
    reg0273_op23zml: new UntypedFormControl({ value: true, disabled: false}),
    reg0273_6pga6ll: new UntypedFormControl({ value: "0", disabled: false}),
    reg0273_eph722y: new UntypedFormControl({ value: "0", disabled: false}),
    reg0273_kspmojd: new UntypedFormControl({ value: "2", disabled: false}),
    reg0279_5znnnnn: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null)]),
    reg027a_3iq5wdd: new UntypedFormControl({ value: "0", disabled: false}),
    reg027a_ytndzhn: new UntypedFormControl({ value: "0", disabled: false}),
    reg027a_gpg5rzd: new UntypedFormControl({ value: "0", disabled: false}),
    reg027b_3iq5wdd: new UntypedFormControl({ value: "0", disabled: false}),
    reg027b_ytndzhn: new UntypedFormControl({ value: "0", disabled: false}),
    reg027b_gpg5rzd: new UntypedFormControl({ value: "0", disabled: false}),
    reg027c_t2pgapn: new UntypedFormControl({ value: "0", disabled: false}),
    reg027c_jv4bm2d: new UntypedFormControl({ value: "0", disabled: false}),
    reg027c_gpg5rzd: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null)]),
    reg027f_m6awtjl: new UntypedFormControl({ value: "1", disabled: false}),
    reg027f_op23zml: new UntypedFormControl({ value: "1", disabled: false}),
    reg027f_bgs5ckd: new UntypedFormControl({ value: "0", disabled: false}),
    reg027f_ooba6wy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02b0_35gzn7y_m6awtjl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02b0_35gzn7y_op23zml: new UntypedFormControl({ value: "0", disabled: false}),
    reg02b0_35gzn7y_ax7h6sl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02b0_35gzn7y_t6r55rl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02b0_35gzn7y_eph722y: new UntypedFormControl({ value: "0", disabled: false}),
    reg02b0_35gzn7y_riuquxn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02b0_35gzn7y_mdwlall: new UntypedFormControl({ value: "0", disabled: false}),
    reg02b0_35gzn7y_ooba6wy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02b1_35gzn7y_flcneal: new UntypedFormControl({ value: "0", disabled: false}),
    reg02b1_35gzn7y_yxum27y: new UntypedFormControl({ value: "0", disabled: false}),
    reg02b1_35gzn7y_riuquxn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02b1_35gzn7y_mdwlall: new UntypedFormControl({ value: "0", disabled: false}),
    reg02b1_35gzn7y_ooba6wy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02bc_35gzn7y_g65secl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02bc_35gzn7y_efr3mkd: new UntypedFormControl({ value: "0", disabled: false}),
    reg02bc_35gzn7y_mdwlall: new UntypedFormControl({ value: "0", disabled: false}),
    reg02bc_35gzn7y_ooba6wy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02be_35gzn7y_rj665vl: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null)]),
    reg02be_35gzn7y_gpg5rzd: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null)]),
    reg02bf: new UntypedFormControl({ value: "FF", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(2), Validators.maxLength(2)])
};
