import { UntypedFormControl } from '@angular/forms';
// @ts-ignore
import { Validators } from '@angular/forms';
// @ts-ignore
import { hexadecimalValidator } from '@shared/directives/hexadecimal.directive';
// @ts-ignore
import { ipValidator } from '@shared/directives/ip.directive';

export const Fpf18175_springcore_h518_puckFormGroup = {
    reg02c0_m6awtjl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c0_eph722y: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c0_kspmojd: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c1_5ymphln_op23zml: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c1_5ymphln_ax7h6sl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c1_5ymphln_t6r55rl: new UntypedFormControl({ value: "1", disabled: false}),
    reg02c1_5ymphln_eph722y: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c1_gcbfcky_riuquxn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c1_5ymphln_khxezgy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c4_snvp4xd: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c4_s27wvjn_ooba6wy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02cd: new UntypedFormControl({ value: "00000000", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(8), Validators.maxLength(8)]),
    reg02ce_fe5kedn_kxpbr2l: new UntypedFormControl({ value: "0", disabled: false}),
    reg02ce_fe5kedn_ax7h6sl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02ce_fe5kedn_t6r55rl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02ce_fe5kedn_l365cmn: new UntypedFormControl({ value: "0", disabled: false}),
    reg0208: new UntypedFormControl({ value: "", disabled: false}, [Validators.maxLength(32)]),
    reg02d0_snvp4xd: new UntypedFormControl({ value: "0", disabled: false}),
    reg02d0_ooba6wy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02d1: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(2), Validators.maxLength(2)]),
    reg02d2_3iq5wdd: new UntypedFormControl({ value: "9", disabled: false}),
    reg02d2_ai7xezy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02d2_gjrcb2n: new UntypedFormControl({ value: "2", disabled: false}),
    reg02d2_5sqf4yy: new UntypedFormControl({ value: "10", disabled: false}),
    reg02d2_k4uiain: new UntypedFormControl({ value: "0", disabled: false}),
    reg02d2_evlcwsl: new UntypedFormControl({ value: "1", disabled: false}),
    reg02d3_lmh6e5y: new UntypedFormControl({ value: "100", disabled: false}),
    reg02d3_gsqqlyn: new UntypedFormControl({ value: "75", disabled: false}),
    reg02d3_rk4pgmy: new UntypedFormControl({ value: "10", disabled: false}),
    reg02d7: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(2), Validators.maxLength(2)]),
    reg02d8_hxqkjly: new UntypedFormControl({ value: "0", disabled: false}),
    reg02d8_kspmojd: new UntypedFormControl({ value: "01", disabled: false}, [hexadecimalValidator(null, null)]),
    reg02d9: new UntypedFormControl({ value: "", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(0), Validators.maxLength(128)]),
    reg02da: new UntypedFormControl({ value: "000000", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(6), Validators.maxLength(6)]),
    reg02a0_6ohabel_aeev4dd: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a0_6ohabel_oe4w4my: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a0_6ohabel_n2k4omn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a0_6ohabel_ups3l5l: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a0_6ohabel_5g4gajl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a0_6ohabel_43kxznd: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a0_6ohabel_rqjiszy: new UntypedFormControl({ value: "3", disabled: false}),
    reg02a0_6ohabel_2j6me3l: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a0_6ohabel_ysqcqsn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a0_6ohabel_vkvtt3n: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a0_6ohabel_sxs7v7d: new UntypedFormControl({ value: "2", disabled: false}),
    reg02a0_6ohabel_flooq3d: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a0_6ohabel_jzirgky: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a1_6ohabel_rj665vl: new UntypedFormControl({ value: "0A", disabled: false}, [hexadecimalValidator(null, null)]),
    reg02a1_6ohabel_gpg5rzd: new UntypedFormControl({ value: "1E", disabled: false}, [hexadecimalValidator(null, null)]),
    reg02a6: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a7: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(2), Validators.maxLength(2)]),
    reg02a8: new UntypedFormControl({ value: "", disabled: false}, [Validators.maxLength(8)]),
    reg02a9: new UntypedFormControl({ value: "\n", disabled: false}, [Validators.maxLength(8)]),
    reg02f0_tdf7qky: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_kkau5nn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_zpy22zy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_iypcdqy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_w2yu4zd: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_y4yzkmn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_3m2xxun: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_noupivn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_xajyakn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_ctwu2dn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_ch4wbsl: new UntypedFormControl({ value: "0", disabled: false}),
    id3767_Note: new UntypedFormControl({ value: "", disabled: false}),
    reg02f2: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(2), Validators.maxLength(2)]),
    reg02f3: new UntypedFormControl({ value: "00000000", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(8), Validators.maxLength(8)]),
    reg02f4: new UntypedFormControl({ value: "00000000000000000000000000000000", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(32), Validators.maxLength(32)]),
    reg02f5: new UntypedFormControl({ value: "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(128), Validators.maxLength(128)]),
    reg02fb_m6awtjl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02fb_op23zml: new UntypedFormControl({ value: "0", disabled: false}),
    reg02fb_ax7h6sl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02fb_t6r55rl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02fb_l365cmn: new UntypedFormControl({ value: "12", disabled: false}),
    reg02fc: new UntypedFormControl({ value: "", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(0), Validators.maxLength(64)]),
    reg02fd: new UntypedFormControl({ value: "", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(0), Validators.maxLength(64)]),
    reg0230_m6awtjl: new UntypedFormControl({ value: "0", disabled: false}),
    reg0230_efr3mkd: new UntypedFormControl({ value: "0", disabled: false}),
    reg0230_mdwlall: new UntypedFormControl({ value: "0", disabled: false}),
    reg0230_ooba6wy: new UntypedFormControl({ value: "1", disabled: false}),
    id3818_Option: new UntypedFormControl({ value: false, disabled: true}),
    id3819_Option: new UntypedFormControl({ value: false, disabled: true}),
    id3820_Option: new UntypedFormControl({ value: false, disabled: false}),
    id3821_Option: new UntypedFormControl({ value: true, disabled: false}),
    id3822_Option: new UntypedFormControl({ value: false, disabled: false}),
    id3823_Option: new UntypedFormControl({ value: true, disabled: false}),
    id3824_Option: new UntypedFormControl({ value: false, disabled: false}),
    id3825_Option: new UntypedFormControl({ value: false, disabled: false}),
    id3826_Option: new UntypedFormControl({ value: true, disabled: false}),
    id3827_Option: new UntypedFormControl({ value: true, disabled: false}),
    id3828_Option: new UntypedFormControl({ value: true, disabled: false}),
    id3829_Option: new UntypedFormControl({ value: false, disabled: false}),
    id3830_Option: new UntypedFormControl({ value: false, disabled: true}),
    id3831_Option: new UntypedFormControl({ value: true, disabled: false}),
    id3832_Option: new UntypedFormControl({ value: true, disabled: false}),
    id3833_Option: new UntypedFormControl({ value: true, disabled: false}),
    id3838_Option: new UntypedFormControl({ value: false, disabled: true}),
    id3839_Option: new UntypedFormControl({ value: false, disabled: false}),
    id3840_Option: new UntypedFormControl({ value: false, disabled: false}),
    id3841_Option: new UntypedFormControl({ value: false, disabled: false}),
    id3842_Option: new UntypedFormControl({ value: false, disabled: true}),
    id3843_Option: new UntypedFormControl({ value: false, disabled: false}),
    id3844_Option: new UntypedFormControl({ value: false, disabled: false}),
    id3845_Option: new UntypedFormControl({ value: false, disabled: false}),
    id3847_Option: new UntypedFormControl({ value: false, disabled: true}),
    id3848_Option: new UntypedFormControl({ value: false, disabled: false}),
    id3849_Option: new UntypedFormControl({ value: false, disabled: false}),
    id3850_Option: new UntypedFormControl({ value: false, disabled: false}),
    id3851_Option: new UntypedFormControl({ value: false, disabled: true}),
    id3852_Option: new UntypedFormControl({ value: false, disabled: false}),
    id3853_Option: new UntypedFormControl({ value: false, disabled: false}),
    id3854_Option: new UntypedFormControl({ value: false, disabled: false}),
    reg0233_35gzn7y_m6awtjl: new UntypedFormControl({ value: "0", disabled: false}),
    reg0233_35gzn7y_op23zml: new UntypedFormControl({ value: "0", disabled: false}),
    reg0233_35gzn7y_ax7h6sl: new UntypedFormControl({ value: "0", disabled: false}),
    reg0233_35gzn7y_t6r55rl: new UntypedFormControl({ value: "0", disabled: false}),
    reg0233_35gzn7y_eph722y: new UntypedFormControl({ value: "0", disabled: false}),
    reg0233_35gzn7y_riuquxn: new UntypedFormControl({ value: "0", disabled: false}),
    reg0233_35gzn7y_mdwlall: new UntypedFormControl({ value: "0", disabled: false}),
    reg0233_35gzn7y_ooba6wy: new UntypedFormControl({ value: "0", disabled: false}),
    reg0234_35gzn7y_m6awtjl: new UntypedFormControl({ value: "0", disabled: false}),
    reg0234_35gzn7y_op23zml: new UntypedFormControl({ value: "0", disabled: false}),
    reg0234_35gzn7y_ax7h6sl: new UntypedFormControl({ value: "0", disabled: false}),
    reg0234_35gzn7y_t6r55rl: new UntypedFormControl({ value: "0", disabled: false}),
    reg0234_35gzn7y_eph722y: new UntypedFormControl({ value: "0", disabled: false}),
    reg0234_35gzn7y_riuquxn: new UntypedFormControl({ value: "0", disabled: false}),
    reg0234_35gzn7y_mdwlall: new UntypedFormControl({ value: "0", disabled: false}),
    reg0234_35gzn7y_ooba6wy: new UntypedFormControl({ value: "0", disabled: false}),
    reg0237_m6awtjl: new UntypedFormControl({ value: "0", disabled: false}),
    reg0237_spf4gny: new UntypedFormControl({ value: "0", disabled: false}),
    reg0237_kspmojd: new UntypedFormControl({ value: "0", disabled: false}),
    reg023a_m6awtjl: new UntypedFormControl({ value: "0", disabled: false}),
    reg023a_op23zml: new UntypedFormControl({ value: true, disabled: false}),
    reg023a_bgs5ckd: new UntypedFormControl({ value: "0", disabled: false}),
    reg023a_ooba6wy: new UntypedFormControl({ value: "0", disabled: false}),
    reg023b_2kglign: new UntypedFormControl({ value: "0", disabled: false}),
    reg023b_7wdxe6d: new UntypedFormControl({ value: true, disabled: false}),
    reg023b_nnfnpnd: new UntypedFormControl({ value: "0", disabled: false}),
    reg023b_jv4bm2d: new UntypedFormControl({ value: "0", disabled: false}),
    reg023b_gpg5rzd: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null)]),
    reg023c_wyhiihy: new UntypedFormControl({ value: "0", disabled: false}),
    reg023c_kq5se4n: new UntypedFormControl({ value: true, disabled: false}),
    reg023c_7ankq7y: new UntypedFormControl({ value: "0", disabled: false}),
    reg023c_af7asbd: new UntypedFormControl({ value: "0", disabled: false}),
    reg023c_b2lvaxl: new UntypedFormControl({ value: "FFFF", disabled: false}, [hexadecimalValidator(null, null)]),
    reg023c_iav4stl: new UntypedFormControl({ value: "01", disabled: false}, [hexadecimalValidator(null, null)]),
    reg023c_n756ral: new UntypedFormControl({ value: "000B", disabled: false}, [hexadecimalValidator(null, null)]),
    reg023c_ehbhexd: new UntypedFormControl({ value: "0009", disabled: false}, [hexadecimalValidator(null, null)]),
    reg023d_rj665vl: new UntypedFormControl({ value: "0", disabled: false}),
    reg023d_gpg5rzd: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null)]),
    reg023e_lmh6e5y: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null)]),
    reg023e_gsqqlyn: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null)]),
    reg023e_rk4pgmy: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null)]),
    reg023f_lngy2qn: new UntypedFormControl({ value: "0", disabled: false}),
    reg023f_5r4ewkl: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null)]),
    reg023f_gsqqlyn: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null)]),
    reg023f_rk4pgmy: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null)]),
    reg0271_m6awtjl: new UntypedFormControl({ value: true, disabled: false}),
    reg0271_op23zml: new UntypedFormControl({ value: true, disabled: false}),
    reg0271_6pga6ll: new UntypedFormControl({ value: "0", disabled: false}),
    reg0271_eph722y: new UntypedFormControl({ value: "0", disabled: false}),
    reg0271_kspmojd: new UntypedFormControl({ value: "3", disabled: false}),
    reg0272_m6awtjl: new UntypedFormControl({ value: true, disabled: false}),
    reg0272_op23zml: new UntypedFormControl({ value: true, disabled: false}),
    reg0272_6pga6ll: new UntypedFormControl({ value: "0", disabled: false}),
    reg0272_eph722y: new UntypedFormControl({ value: "0", disabled: false}),
    reg0272_kspmojd: new UntypedFormControl({ value: "2", disabled: false}),
    reg0273_m6awtjl: new UntypedFormControl({ value: true, disabled: false}),
    reg0273_op23zml: new UntypedFormControl({ value: true, disabled: false}),
    reg0273_6pga6ll: new UntypedFormControl({ value: "0", disabled: false}),
    reg0273_eph722y: new UntypedFormControl({ value: "0", disabled: false}),
    reg0273_kspmojd: new UntypedFormControl({ value: "2", disabled: false}),
    reg0279_5znnnnn: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null)]),
    reg027a_3iq5wdd: new UntypedFormControl({ value: "0", disabled: false}),
    reg027a_ytndzhn: new UntypedFormControl({ value: "0", disabled: false}),
    reg027a_gpg5rzd: new UntypedFormControl({ value: "0", disabled: false}),
    reg027b_3iq5wdd: new UntypedFormControl({ value: "0", disabled: false}),
    reg027b_ytndzhn: new UntypedFormControl({ value: "0", disabled: false}),
    reg027b_gpg5rzd: new UntypedFormControl({ value: "0", disabled: false}),
    reg027c_t2pgapn: new UntypedFormControl({ value: "0", disabled: false}),
    reg027c_jv4bm2d: new UntypedFormControl({ value: "0", disabled: false}),
    reg027c_gpg5rzd: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null)]),
    reg027f_m6awtjl: new UntypedFormControl({ value: "1", disabled: false}),
    reg027f_op23zml: new UntypedFormControl({ value: "1", disabled: false}),
    reg027f_bgs5ckd: new UntypedFormControl({ value: "0", disabled: false}),
    reg027f_ooba6wy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02b0_35gzn7y_m6awtjl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02b0_35gzn7y_op23zml: new UntypedFormControl({ value: "0", disabled: false}),
    reg02b0_35gzn7y_ax7h6sl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02b0_35gzn7y_t6r55rl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02b0_35gzn7y_eph722y: new UntypedFormControl({ value: "0", disabled: false}),
    reg02b0_35gzn7y_riuquxn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02b0_35gzn7y_mdwlall: new UntypedFormControl({ value: "0", disabled: false}),
    reg02b0_35gzn7y_ooba6wy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02b1_35gzn7y_flcneal: new UntypedFormControl({ value: "0", disabled: false}),
    reg02b1_35gzn7y_yxum27y: new UntypedFormControl({ value: "0", disabled: false}),
    reg02b1_35gzn7y_riuquxn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02b1_35gzn7y_mdwlall: new UntypedFormControl({ value: "0", disabled: false}),
    reg02b1_35gzn7y_ooba6wy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02bc_35gzn7y_g65secl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02bc_35gzn7y_efr3mkd: new UntypedFormControl({ value: "0", disabled: false}),
    reg02bc_35gzn7y_mdwlall: new UntypedFormControl({ value: "0", disabled: false}),
    reg02bc_35gzn7y_ooba6wy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02be_35gzn7y_rj665vl: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null)]),
    reg02be_35gzn7y_gpg5rzd: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null)]),
    reg02bf: new UntypedFormControl({ value: "FF", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(2), Validators.maxLength(2)]),
    reg02e0_snvp4xd: new UntypedFormControl({ value: "0", disabled: false}),
    reg02e0_ooba6wy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02eb: new UntypedFormControl({ value: "", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(0), Validators.maxLength(32)]),
    reg02ec: new UntypedFormControl({ value: "", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(0), Validators.maxLength(32)]),
    reg02ed: new UntypedFormControl({ value: "", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(0), Validators.maxLength(128)])
};
