import { UntypedFormControl } from '@angular/forms';
// @ts-ignore
import { Validators } from '@angular/forms';
// @ts-ignore
import { hexadecimalValidator } from '@shared/directives/hexadecimal.directive';
// @ts-ignore
import { ipValidator } from '@shared/directives/ip.directive';

export const Ean18036_springcore_e993_crazyuhfFormGroup = {
    reg02c0_m6awtjl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c0_dlvtahl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c0_eph722y: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c0_kspmojd: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c1_m6awtjl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c1_5ymphln_op23zml: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c1_5ymphln_ax7h6sl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c1_5ymphln_t6r55rl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c1_5ymphln_eph722y: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c1_gcbfcky_riuquxn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c1_5ymphln_khxezgy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c4_snvp4xd: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c4_s27wvjn_ooba6wy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02cd: new UntypedFormControl({ value: "00000000", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(8), Validators.maxLength(8)]),
    reg02ce_fe5kedn_kxpbr2l: new UntypedFormControl({ value: "0", disabled: false}),
    reg02ce_fe5kedn_ax7h6sl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02ce_fe5kedn_t6r55rl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02ce_fe5kedn_l365cmn: new UntypedFormControl({ value: "0", disabled: false}),
    reg0208: new UntypedFormControl({ value: "", disabled: false}, [Validators.maxLength(32)]),
    reg0283_m6awtjl: new UntypedFormControl({ value: "0", disabled: false}),
    reg0283_op23zml: new UntypedFormControl({ value: "0", disabled: false}),
    reg0283_5lnxfcy: new UntypedFormControl({ value: "0", disabled: false}),
    reg0283_kspmojd: new UntypedFormControl({ value: "0", disabled: false}),
    reg0284_g65secl: new UntypedFormControl({ value: "0", disabled: false}),
    reg0284_efr3mkd: new UntypedFormControl({ value: "1", disabled: false}),
    reg0284_mdwlall: new UntypedFormControl({ value: "0", disabled: false}),
    reg0284_ooba6wy: new UntypedFormControl({ value: "0", disabled: false}),
    reg0285_r2fsrhn: new UntypedFormControl({ value: "0000", disabled: false}, [hexadecimalValidator(null, null)]),
    reg0285_57ht7bn: new UntypedFormControl({ value: "0000", disabled: false}, [hexadecimalValidator(null, null)]),
    reg0285_2wtrxwn: new UntypedFormControl({ value: "0000", disabled: false}, [hexadecimalValidator(null, null)]),
    reg0285_huvv3cl: new UntypedFormControl({ value: "0000", disabled: false}, [hexadecimalValidator(null, null)]),
    reg0285_5zgsj4y: new UntypedFormControl({ value: "0000", disabled: false}, [hexadecimalValidator(null, null)]),
    reg0285_7cpcu7y: new UntypedFormControl({ value: "0000", disabled: false}, [hexadecimalValidator(null, null)]),
    reg0285_g6f77fn: new UntypedFormControl({ value: "0000", disabled: false}, [hexadecimalValidator(null, null)]),
    reg0286: new UntypedFormControl({ value: "", disabled: false}, [Validators.maxLength(48)]),
    reg0288_jxfrlfn_f5bc2vy: new UntypedFormControl({ value: "0", disabled: false}),
    reg0288_jxfrlfn_pelr6in: new UntypedFormControl({ value: "0", disabled: false}),
    reg0288_jxfrlfn_hz4o5wy: new UntypedFormControl({ value: "0", disabled: false}),
    reg0288_jxfrlfn_6tkjtun: new UntypedFormControl({ value: "0", disabled: false}),
    reg0288_jxfrlfn_wfsxvul: new UntypedFormControl({ value: "0", disabled: false}),
    reg0288_jxfrlfn_ups3l5l: new UntypedFormControl({ value: "0", disabled: false}),
    reg0288_jxfrlfn_5g4gajl: new UntypedFormControl({ value: "0", disabled: false}),
    reg0288_jxfrlfn_l4bfvfd: new UntypedFormControl({ value: "0", disabled: false}),
    reg0288_jxfrlfn_ptn6fqy: new UntypedFormControl({ value: "0", disabled: false}),
    reg0288_jxfrlfn_czj6tml: new UntypedFormControl({ value: "0", disabled: false}),
    reg0288_jxfrlfn_qjkt6pl: new UntypedFormControl({ value: "0", disabled: false}),
    reg0288_jxfrlfn_ti5jnln: new UntypedFormControl({ value: "0", disabled: false}),
    reg0288_jxfrlfn_4uhbnoy: new UntypedFormControl({ value: "0", disabled: false}),
    reg0288_jxfrlfn_vxqhved: new UntypedFormControl({ value: "0", disabled: false}),
    reg0288_jxfrlfn_lwafuod: new UntypedFormControl({ value: "0", disabled: false}),
    reg0288_jxfrlfn_xfgml2l: new UntypedFormControl({ value: "0", disabled: false}),
    reg0288_jxfrlfn_qypyhll: new UntypedFormControl({ value: "0", disabled: false}),
    reg0288_jxfrlfn_3rf6ivn: new UntypedFormControl({ value: "0", disabled: false}),
    reg0289_jxfrlfn_onij6xy: new UntypedFormControl({ value: "1", disabled: false}),
    reg0289_jxfrlfn_77z3hvd: new UntypedFormControl({ value: "1", disabled: false}),
    reg0289_jxfrlfn_j7lqmpd: new UntypedFormControl({ value: "0", disabled: false}),
    reg0289_jxfrlfn_xkk6mgl: new UntypedFormControl({ value: "0", disabled: false}),
    reg0289_jxfrlfn_5dxn43n: new UntypedFormControl({ value: "1", disabled: false}),
    reg0289_jxfrlfn_232mc4d: new UntypedFormControl({ value: "1", disabled: false}),
    reg0289_jxfrlfn_2fpwhjy: new UntypedFormControl({ value: "14", disabled: false}, [hexadecimalValidator(null, null)]),
    reg0289_jxfrlfn_g5vrfod: new UntypedFormControl({ value: "03", disabled: false}, [hexadecimalValidator(null, null)]),
    reg0289_jxfrlfn_4agk3pd: new UntypedFormControl({ value: "0A", disabled: false}, [hexadecimalValidator(null, null)]),
    reg0289_jxfrlfn_cjpxtol: new UntypedFormControl({ value: "1E", disabled: false}, [hexadecimalValidator(null, null)]),
    reg0289_jxfrlfn_ppnczjd: new UntypedFormControl({ value: "1E", disabled: false}, [hexadecimalValidator(null, null)]),
    reg028b: new UntypedFormControl({ value: "", disabled: false}, [Validators.maxLength(16)]),
    reg028c: new UntypedFormControl({ value: "", disabled: false}, [Validators.maxLength(16)]),
    reg028d: new UntypedFormControl({ value: "", disabled: false}, [Validators.maxLength(24)]),
    reg028e: new UntypedFormControl({ value: "springcard/springcore", disabled: false}, [Validators.maxLength(32)]),
    reg028f: new UntypedFormControl({ value: "", disabled: false}, [Validators.maxLength(24)]),
    reg0290: new UntypedFormControl({ value: "rdr.springcard.com", disabled: false}, [Validators.maxLength(48)]),
    reg0291: new UntypedFormControl({ value: "iwm2/iwm2_post.php", disabled: false}, [Validators.maxLength(48)]),
    reg0292_yzzpvwy_rj665vl: new UntypedFormControl({ value: "1E", disabled: false}, [hexadecimalValidator(null, null)]),
    reg0292_yzzpvwy_gpg5rzd: new UntypedFormControl({ value: "3C", disabled: false}, [hexadecimalValidator(null, null)]),
    reg0293: new UntypedFormControl({ value: "", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(0), Validators.maxLength(64)]),
    reg02d0_snvp4xd: new UntypedFormControl({ value: "0", disabled: false}),
    reg02d0_ooba6wy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02d1: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(2), Validators.maxLength(2)]),
    reg02d2_3iq5wdd: new UntypedFormControl({ value: "9", disabled: false}),
    reg02d2_ai7xezy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02d2_gjrcb2n: new UntypedFormControl({ value: "2", disabled: false}),
    reg02d2_5sqf4yy: new UntypedFormControl({ value: "10", disabled: false}),
    reg02d2_k4uiain: new UntypedFormControl({ value: "0", disabled: false}),
    reg02d2_evlcwsl: new UntypedFormControl({ value: "1", disabled: false}),
    reg02d3_lmh6e5y: new UntypedFormControl({ value: "100", disabled: false}),
    reg02d3_gsqqlyn: new UntypedFormControl({ value: "75", disabled: false}),
    reg02d3_rk4pgmy: new UntypedFormControl({ value: "10", disabled: false}),
    reg02d7: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(2), Validators.maxLength(2)]),
    reg02d8_hxqkjly: new UntypedFormControl({ value: "0", disabled: false}),
    reg02d8_kspmojd: new UntypedFormControl({ value: "01", disabled: false}, [hexadecimalValidator(null, null)]),
    reg02d9: new UntypedFormControl({ value: "", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(0), Validators.maxLength(128)]),
    reg02da: new UntypedFormControl({ value: "000000", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(6), Validators.maxLength(6)]),
    reg02a0_6ohabel_aeev4dd: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a0_6ohabel_oe4w4my: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a0_6ohabel_n2k4omn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a0_6ohabel_ups3l5l: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a0_6ohabel_5g4gajl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a0_6ohabel_43kxznd: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a0_6ohabel_rqjiszy: new UntypedFormControl({ value: "3", disabled: false}),
    reg02a0_6ohabel_2j6me3l: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a0_6ohabel_ysqcqsn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a0_6ohabel_vkvtt3n: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a0_6ohabel_sxs7v7d: new UntypedFormControl({ value: "2", disabled: false}),
    reg02a0_6ohabel_flooq3d: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a0_6ohabel_jzirgky: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a1_6ohabel_rj665vl: new UntypedFormControl({ value: "0A", disabled: false}, [hexadecimalValidator(null, null)]),
    reg02a1_6ohabel_gpg5rzd: new UntypedFormControl({ value: "1E", disabled: false}, [hexadecimalValidator(null, null)]),
    reg02a6: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a7: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(2), Validators.maxLength(2)]),
    reg02a8: new UntypedFormControl({ value: "", disabled: false}, [Validators.maxLength(8)]),
    reg02a9: new UntypedFormControl({ value: "\n", disabled: false}, [Validators.maxLength(8)]),
    reg02f0_y4yzkmn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_3m2xxun: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_noupivn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_xajyakn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_ctwu2dn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_ch4wbsl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_vjvofiy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_rc6tnwl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_5y4fpey: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_awfi3xn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_loo4own: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_4koytuy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_uld4ejn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_n6f65hn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_x62ifjd: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_cyos74l: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_taxjzhn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_3t465bd: new UntypedFormControl({ value: "0", disabled: false}),
    id980_Note: new UntypedFormControl({ value: "", disabled: false}),
    reg02f1_3iq5wdd: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f1_ytndzhn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f1_5sqf4yy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f1_rxpn6ed: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f2: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(2), Validators.maxLength(2)]),
    reg02f3: new UntypedFormControl({ value: "00000000", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(8), Validators.maxLength(8)]),
    reg02f4: new UntypedFormControl({ value: "00000000000000000000000000000000", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(32), Validators.maxLength(32)]),
    reg02f5: new UntypedFormControl({ value: "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(128), Validators.maxLength(128)]),
    id1010_Option: new UntypedFormControl({ value: false, disabled: true}),
    id1011_Option: new UntypedFormControl({ value: false, disabled: true}),
    id1012_Option: new UntypedFormControl({ value: false, disabled: true}),
    id1013_Option: new UntypedFormControl({ value: false, disabled: true}),
    id1014_Option: new UntypedFormControl({ value: false, disabled: true}),
    id1015_Option: new UntypedFormControl({ value: true, disabled: false}),
    id1016_Option: new UntypedFormControl({ value: false, disabled: true}),
    id1017_Option: new UntypedFormControl({ value: false, disabled: true}),
    id1025_Option: new UntypedFormControl({ value: false, disabled: true}),
    id1026_Option: new UntypedFormControl({ value: false, disabled: true}),
    id1027_Option: new UntypedFormControl({ value: false, disabled: true}),
    id1028_Option: new UntypedFormControl({ value: false, disabled: true}),
    id1029_Option: new UntypedFormControl({ value: false, disabled: true}),
    id1030_Option: new UntypedFormControl({ value: false, disabled: true}),
    id1031_Option: new UntypedFormControl({ value: false, disabled: true}),
    id1032_Option: new UntypedFormControl({ value: false, disabled: false}),
    reg0267: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(2), Validators.maxLength(2)]),
    reg0294: new UntypedFormControl({ value: "255.255.255.255", disabled: false}, [Validators.maxLength(48)]),
    reg0295_u4kds4n_hycivfd: new UntypedFormControl({ value: "0", disabled: false}),
    reg0295_u4kds4n_mdwlall: new UntypedFormControl({ value: "0", disabled: false}),
    reg0295_u4kds4n_ooba6wy: new UntypedFormControl({ value: "0", disabled: false}),
    reg029c_t2pgapn: new UntypedFormControl({ value: "0", disabled: false}),
    reg029c_jv4bm2d: new UntypedFormControl({ value: "1", disabled: false}),
    reg029c_gpg5rzd: new UntypedFormControl({ value: "03", disabled: false}, [hexadecimalValidator(null, null)])
};
