import { UntypedFormControl } from '@angular/forms';
// @ts-ignore
import { Validators } from '@angular/forms';
// @ts-ignore
import { hexadecimalValidator } from '@shared/directives/hexadecimal.directive';
// @ts-ignore
import { ipValidator } from '@shared/directives/ip.directive';

export const Ean18035_springcore_h993_crazyuhfFormGroup = {
    reg02c0_m6awtjl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c0_eph722y: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c0_kspmojd: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c1_m6awtjl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c1_5ymphln_op23zml: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c1_5ymphln_ax7h6sl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c1_5ymphln_t6r55rl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c1_5ymphln_eph722y: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c1_gcbfcky_riuquxn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c1_5ymphln_khxezgy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c4_snvp4xd: new UntypedFormControl({ value: "0", disabled: false}),
    reg02c4_s27wvjn_ooba6wy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02cd: new UntypedFormControl({ value: "00000000", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(8), Validators.maxLength(8)]),
    reg02ce_fe5kedn_kxpbr2l: new UntypedFormControl({ value: "0", disabled: false}),
    reg02ce_fe5kedn_ax7h6sl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02ce_fe5kedn_t6r55rl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02ce_fe5kedn_l365cmn: new UntypedFormControl({ value: "0", disabled: false}),
    reg0208: new UntypedFormControl({ value: "", disabled: false}, [Validators.maxLength(32)]),
    reg02d0_snvp4xd: new UntypedFormControl({ value: "0", disabled: false}),
    reg02d0_ooba6wy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02d1: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(2), Validators.maxLength(2)]),
    reg02d2_3iq5wdd: new UntypedFormControl({ value: "9", disabled: false}),
    reg02d2_ai7xezy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02d2_gjrcb2n: new UntypedFormControl({ value: "2", disabled: false}),
    reg02d2_5sqf4yy: new UntypedFormControl({ value: "10", disabled: false}),
    reg02d2_k4uiain: new UntypedFormControl({ value: "0", disabled: false}),
    reg02d2_evlcwsl: new UntypedFormControl({ value: "1", disabled: false}),
    reg02d3_lmh6e5y: new UntypedFormControl({ value: "100", disabled: false}),
    reg02d3_gsqqlyn: new UntypedFormControl({ value: "75", disabled: false}),
    reg02d3_rk4pgmy: new UntypedFormControl({ value: "10", disabled: false}),
    reg02d7: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(2), Validators.maxLength(2)]),
    reg02d8_hxqkjly: new UntypedFormControl({ value: "0", disabled: false}),
    reg02d8_kspmojd: new UntypedFormControl({ value: "01", disabled: false}, [hexadecimalValidator(null, null)]),
    reg02d9: new UntypedFormControl({ value: "", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(0), Validators.maxLength(128)]),
    reg02da: new UntypedFormControl({ value: "000000", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(6), Validators.maxLength(6)]),
    reg02a0_6ohabel_aeev4dd: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a0_6ohabel_oe4w4my: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a0_6ohabel_n2k4omn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a0_6ohabel_ups3l5l: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a0_6ohabel_5g4gajl: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a0_6ohabel_43kxznd: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a0_6ohabel_rqjiszy: new UntypedFormControl({ value: "3", disabled: false}),
    reg02a0_6ohabel_2j6me3l: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a0_6ohabel_ysqcqsn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a0_6ohabel_vkvtt3n: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a0_6ohabel_sxs7v7d: new UntypedFormControl({ value: "2", disabled: false}),
    reg02a0_6ohabel_flooq3d: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a0_6ohabel_jzirgky: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a1_6ohabel_rj665vl: new UntypedFormControl({ value: "0A", disabled: false}, [hexadecimalValidator(null, null)]),
    reg02a1_6ohabel_gpg5rzd: new UntypedFormControl({ value: "1E", disabled: false}, [hexadecimalValidator(null, null)]),
    reg02a6: new UntypedFormControl({ value: "0", disabled: false}),
    reg02a7: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(2), Validators.maxLength(2)]),
    reg02a8: new UntypedFormControl({ value: "", disabled: false}, [Validators.maxLength(8)]),
    reg02a9: new UntypedFormControl({ value: "\n", disabled: false}, [Validators.maxLength(8)]),
    reg02f0_y4yzkmn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_3m2xxun: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_noupivn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_xajyakn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_ctwu2dn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f0_ch4wbsl: new UntypedFormControl({ value: "0", disabled: false}),
    id1312_Note: new UntypedFormControl({ value: "", disabled: false}),
    reg02f1_3iq5wdd: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f1_ytndzhn: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f1_5sqf4yy: new UntypedFormControl({ value: "0", disabled: false}),
    reg02f1_rxpn6ed: new UntypedFormControl({ value: "0", disabled: false}),
    id1326_Option: new UntypedFormControl({ value: false, disabled: true}),
    id1327_Option: new UntypedFormControl({ value: false, disabled: true}),
    id1328_Option: new UntypedFormControl({ value: false, disabled: true}),
    id1329_Option: new UntypedFormControl({ value: false, disabled: true}),
    id1330_Option: new UntypedFormControl({ value: false, disabled: true}),
    id1331_Option: new UntypedFormControl({ value: true, disabled: false}),
    id1332_Option: new UntypedFormControl({ value: false, disabled: true}),
    id1333_Option: new UntypedFormControl({ value: false, disabled: true}),
    id1341_Option: new UntypedFormControl({ value: false, disabled: true}),
    id1342_Option: new UntypedFormControl({ value: false, disabled: true}),
    id1343_Option: new UntypedFormControl({ value: false, disabled: true}),
    id1344_Option: new UntypedFormControl({ value: false, disabled: true}),
    id1345_Option: new UntypedFormControl({ value: false, disabled: true}),
    id1346_Option: new UntypedFormControl({ value: false, disabled: true}),
    id1347_Option: new UntypedFormControl({ value: false, disabled: true}),
    id1348_Option: new UntypedFormControl({ value: false, disabled: false}),
    reg0267: new UntypedFormControl({ value: "00", disabled: false}, [hexadecimalValidator(null, null), Validators.minLength(2), Validators.maxLength(2)]),
    reg029c_t2pgapn: new UntypedFormControl({ value: "0", disabled: false}),
    reg029c_jv4bm2d: new UntypedFormControl({ value: "1", disabled: false}),
    reg029c_gpg5rzd: new UntypedFormControl({ value: "03", disabled: false}, [hexadecimalValidator(null, null)])
};
